{% set name = "aiocsv" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiocsv-{{ version }}.tar.gz
  sha256: 806d93465c7808d58d3ff0d2bba270fb4d04b934be6a1e95d0834c50a510910e

build:
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python
    - typing_extensions

test:
  imports:
    - aiocsv
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/MKuranowski/aiocsv
  summary: Asynchronous CSV reading/writing
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - apmorton
